3.6: Client-side app routing
jamkerr/ymdb-client pull request #5
Opened 2022-12-06 16:23 UTC by jamkerr

This PR includes:
- Genre view, Director view, and Profile view
- Routing and navigation between pages
- Navbar

2022-12-07 06:29 UTC, oxenprogrammer requested changes
I have left some few suggestions to fix some of your bugs but not all.
To avoid prop drilling. We can use [useContext Hook](https://beta.reactjs.org/apis/react/useContext).

2022-12-07 06:29 UTC, oxenprogrammer commented on src/components/main-view/main-view.jsx
> +    }, [user]);
```suggestion
    }, [token]);
```

2022-12-07 06:29 UTC, oxenprogrammer commented on src/components/main-view/main-view.jsx
> +    }, [user]);
The side effect (dependency) here is `token` not `user`

2022-12-07 06:29 UTC, oxenprogrammer commented on src/components/profile-view/profile-view.jsx
> +    }, [userData]);
```suggestion
    }, []);
```

2022-12-07 06:29 UTC, oxenprogrammer commented on src/components/profile-view/profile-view.jsx
> +    }, [userData]);
`userData` cannot be a side effect here. IMO it should be an empty array.

2022-12-07 06:29 UTC, oxenprogrammer commented on src/components/profile-view/profile-view.jsx
> +                <Row>
I think the profile sometimes doesn't load because of the `userData.FavoriteMovies` being undefined sometimes. 
I tried a ternary operator but the error persisted for some time.

2022-12-07 06:29 UTC, oxenprogrammer commented on src/components/navbar/navbar.jsx
> +                            <Nav.Link href='/login'>Sign in</Nav.Link>
```suggestion
                            <Nav.Link href='/'>Sign in</Nav.Link>
```

2022-12-07 06:29 UTC, oxenprogrammer commented on src/components/favourite-button/favourite-button.jsx
> +
```suggestion
import { useState } from 'react;
```

2022-12-07 06:29 UTC, oxenprogrammer commented on src/components/favourite-button/favourite-button.jsx
> +    const isFavorite = favouriteMovies.includes(movie._id);
```suggestion
    const [favorite, setFavorite] = useState(false);
    const isFavorite = favouriteMovies.includes(movie._id);
```

2022-12-07 06:29 UTC, oxenprogrammer commented on src/components/favourite-button/favourite-button.jsx
> +}
```suggestion
            try {
                setFavorite((prev) => !prev);
                await axios.delete(`https://ymdeebee.herokuapp.com/users/${Username}/favorites/${movieTitle}`, {
                    headers: { Authorization: `Bearer ${token}` }
                });
            } catch (error) {
                console.error(error, 'Could not remove movie from favorites');
            }
        }
        // Add movie if id does not exist in Favorite movies
        if (isFavorite === false) {
            try {
                setFavorite((prev) => !prev);
                await axios.put(`https://ymdeebee.herokuapp.com/users/${Username}/favorites/${movieTitle}`, {}, {
                    headers: { Authorization: `Bearer ${token}` }
                });
            } catch (error) {
                console.error(error, 'Could not add movie to favorites');
            }
        }
    }

    return (
        <Button
            onClick={() => toggleFavorite(movie.Title)}
            className="favorite-button"
            key={movie._Id}
        >
            {favorite ? unfavIcon : favIcon}
        </Button>
    )
}
```

2022-12-07 06:29 UTC, oxenprogrammer commented on src/components/favourite-button/favourite-button.jsx
> +}
This will help with `Toggle` but also you have work to do to see that it deletes from the view on the profile.

2022-12-12 10:33 UTC, jamkerr commented on src/components/profile-view/profile-view.jsx
> +                <Row>
I still haven't found a solution for this. I'm resolving it for now, but will continue to work on it in the next branch.

2022-12-12 10:34 UTC, merged